# Setup
title:        YCBS 273 - qwerewt Practical Machine Learning
tagline:      A crash course in deep learning
baseurl:      "/ycbs273"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Komal Teru
  url:        http://kkteru.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
