# Setup
title:        YCBS 273 - Practical Machine Learning
tagline:      A crash course in deep learning
baseurl:      "/~kteru/ycbs273"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Komal Teru
  url:        ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
