# Setup
title:        YCBS 273 - Practical Machine Learning
tagline:      A crash course in deep learning
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Komal Teru
  url:        http://localhost:4000

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
